#!/bin/bash

osascript <<EOF
tell application "Terminal"
    set ProfilesNames to name of every settings set
    repeat with ProfileName in ProfilesNames
        set font name of settings set ProfileName to "MesloLGS NF"
        set font size of settings set ProfileName to 11
    end repeat
end tell
EOF
