#!/bin/bash -e

# Install brew dependencies.
install_brew() {
  echo "Running brew..."
  brew bundle --file=brew/Brewfile
}

# Install oh-my-zsh.
install_oh-my-zsh() {
  DIR="$HOME/.oh-my-zsh"
  if [ -d "$DIR" ]; then
    echo "Existing installation found in  ${DIR}...skipping oh-my-zsh installation."
    return 0;
  else
    echo "Installing oh-my-zsh..."
    # Install oh-my-zsh.
    # sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  fi
}

# Setup rc files.
symlink_dotfiles() {
  echo "Symlinking dotfiles..."
  rcup -fvd packages | nl -bn
}

# Configure macOS defaults.
configure_macos() {
  echo "Applying macOS defaults..."
  source macos/defaults
}

# Configure duti default file handlers.
configure_duti() {
  echo "Applying duti defaults..."

  # VS Code
  local vsCodeExtensions=(json md py sh yaml yml)
  for extension in "${vsCodeExtensions[@]}"
  do
    duti -s com.microsoft.VSCode .${extension} all
  done

  # The Unarchiver
  local unarchiverExtensions=(zip rar)
  for extension in "${unarchiverExtensions[@]}"
  do
    duti -s com.macpaw.site.theunarchiver .${extension} all
  done
}



install_brew
install_oh-my-zsh
symlink_dotfiles
# configure_macos
configure_duti
