#!/bin/bash

export VAGRANT_CWD=$HOME/tools/podman

ACTION=$1

case $ACTION in
  "down")
    echo "Shutting down podman"
    vagrant halt
    ;;

  "up")
    echo "STARTING podman"
    vagrant up
    ;;

esac
