Vagrant.configure("2") do |config|
  config.vm.box = "fedora/34-cloud-base"
  config.vm.hostname = "pman"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.provision "shell", inline: <<-SHELL

    ssh-keygen -b 4096 -t rsa -f ~/.ssh/pman -q -N '' -C "pman-vagrant"
    ssh-add ~/.ssh/pman

    ssh-copy-id -o StrictHostKeyChecking=no -f -i ~/.ssh/pman.pub vagrant@127.0.0.1 -p 2222
    ssh -p 2222 vagrant@127.0.0.1

    sudo dnf --enablerepo=updates-testing install -y podman libvarlink-util libvarlink

    systemctl --user enable --now podman
    sudo loginctl enable-linger $USER

    sudo groupadd -f -r podman
    podman --remote info
    sudo systemctl enable --now sshd

    #systemctl edit podman.socket
    mkdir -p /etc/systemd/system/podman.socket.d

    systemctl --user enable --now podman.socket
    sudo loginctl enable-linger $USER
    sudo systemctl enable --now sshd

    cat >/etc/systemd/system/podman.socket.d/override.conf <<EOF
[Socket]
SocketMode=0660
SocketUser=root
SocketGroup=podman
EOF
    systemctl daemon-reload
    echo "d /run/podman 0770 root podman" > /etc/tmpfiles.d/podman.conf
    sudo systemd-tmpfiles --create

    systemctl enable podman.socket
    systemctl start podman.socket

    usermod -aG podman $SUDO_USER


  SHELL
end
